# Generated by Django 4.0.5 on 2022-06-12 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
