# Generated by Django 4.0.5 on 2022-06-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate_context',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Trash'), (2, '2 - Horrible'), (3, '3 - Terrible'), (4, '4 - Bad'), (5, '5 - Ok'), (6, '6 - Satisfactory'), (7, '7 - Good'), (8, '8 - Amazing'), (9, '9 - Perfect'), (10, '10 - Master Piece')], default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rate_usability',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Trash'), (2, '2 - Horrible'), (3, '3 - Terrible'), (4, '4 - Bad'), (5, '5 - Ok'), (6, '6 - Satisfactory'), (7, '7 - Good'), (8, '8 - Amazing'), (9, '9 - Perfect'), (10, '10 - Master Piece')], default=0),
        ),
    ]
