# Generated by Django 4.0.5 on 2022-06-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_review_rate_context_review_rate_usability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rate_context',
            new_name='rate_content',
        ),
    ]
